### ISSUE TITLE
Insecure error response on GET /polls

### ISSUE THREAD

**Issue by sergeyklay** [Yobmod/dmlsite#15]
Hello,

Just noticed that when I open https://dmlsite.herokuapp.com/polls/ Django displays an error page intended for local development only
<img width="911" alt="image" src="https://user-images.githubusercontent.com/1256298/131247091-d8120776-c85b-4a6a-a33d-19380a09e3a4.png">

**Comment by Yobmod** [comment]
Thanks for the headsup!

**Comment by sergeyklay** [comment]
You're welcome :)
